### ISSUE TITLE
App Crashes on Start

### ISSUE THREAD

**Issue by casper123** [infil00p/cordova-crosswalk-engine#45]
I am unable to run my app with any of the crosswalk versions. The app crashes immedietly on start. 
Here is the log, i'm really not sure about the issue

```
root@Abduls-MacBook-Air.local:/Users/abdulwahab/Documents/mobileapps/newnovitrix$adb logcat | grep walk
D/XWalkLib( 3425): Pre init xwalk core in com.novitrix.nerdhyve.MainActivity
D/XWalkLib( 3425): Reserve class class org.xwalk.core.XWalkPreferences to com.novitrix.nerdhyve.MainActivity
D/XWalkLib( 3425): Reserve class class org.xwalk.core.XWalkPreferences to com.novitrix.nerdhyve.MainActivity
D/XWalkLib( 3425): Reserve class class org.xwalk.core.XWalkPreferences to com.novitrix.nerdhyve.MainActivity
D/XWalkLib( 3425): Reserve class class org.xwalk.core.XWalkPreferences to com.novitrix.nerdhyve.MainActivity
D/XWalkLib( 3425): Reserve object class org.crosswalk.engine.XWalkCordovaView to com.novitrix.nerdhyve.MainActivity
D/XWalkLib( 3425): Reserve object class org.crosswalk.engine.XWalkCordovaResourceClient to com.novitrix.nerdhyve.MainActivity
D/XWalkLib( 3425): Reserve object class org.crosswalk.engine.XWalkCordovaUiClient to com.novitrix.nerdhyve.MainActivity
D/XWalkLib( 3425): Attach xwalk core
I/dalvikvm( 3425): DexOpt: unable to optimize static field ref 0x01be at 0x33 in Lorg/xwalk/core/internal/XWalkViewDelegate;.<clinit>
I/dalvikvm( 3425): DexOpt: unable to optimize static field ref 0x01be at 0x43 in Lorg/xwalk/core/internal/XWalkViewDelegate;.<clinit>
D/XWalkLib( 3425): java.lang.UnsatisfiedLinkError: Couldn't load xwalkcore from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.novitrix.nerdhyve-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.novitrix.nerdhyve-1, /vendor/lib, /system/lib]]]: findLibrary returned null
D/dalvikvm( 3425): Trying to load lib /data/data/com.novitrix.nerdhyve/app_xwalkcore/libxwalkcore.so 0x411e03d8
E/linker  ( 3425): load_library(linker.cpp:759): library "/data/data/com.novitrix.nerdhyve/app_xwalkcore/libxwalkcore.so" not found
E/dalvikvm( 3425): dlopen("/data/data/com.novitrix.nerdhyve/app_xwalkcore/libxwalkcore.so") failed: Cannot load library: load_library(linker.cpp:759): library "/data/data/com.novitrix.nerdhyve/app_xwalkcore/libxwalkcore.so" not found
D/XWalkLib( 3425): java.lang.UnsatisfiedLinkError: Cannot load library: load_library(linker.cpp:759): library "/data/data/com.novitrix.nerdhyve/app_xwalkcore/libxwalkcore.so" not found
D/XWalkLib( 3425): Created package context for org.xwalk.core
D/dalvikvm( 3425): open_cached_dex_file : /data/app/org.xwalk.core-1.apk /data/dalvik-cache/data@app@org.xwalk.core-1.apk@classes.dex
D/dalvikvm( 3425): Trying to load lib /data/app-lib/org.xwalk.core-1/libxwalkcore.so 0x4126ce28
D/dalvikvm( 3425): Added shared lib /data/app-lib/org.xwalk.core-1/libxwalkcore.so 0x4126ce28
D/dalvikvm( 3425): Trying to load lib /data/app-lib/org.xwalk.core-1/libxwalkcore.so 0x4126ce28
D/dalvikvm( 3425): Shared lib '/data/app-lib/org.xwalk.core-1/libxwalkcore.so' already loaded in same CL 0x4126ce28
D/XWalkLib( 3425): Dock xwalk core
D/XWalkLib( 3425): Init xwalk view
W/XWalkInternalResources( 3425): org.xwalk.core.R$styleable.ButtonCompat is not int.
W/XWalkInternalResources( 3425): org.xwalk.core.R$dimen.keyboard_accessory_fading_edge_length is not found.
W/XWalkInternalResources( 3425): org.xwalk.core.R$styleable.ButtonCompat is not int.
W/XWalkInternalResources( 3425): org.xwalk.core.R$dimen.keyboard_accessory_fading_edge_length is not found.
W/XWalkInternalResources( 3425): org.xwalk.core.R$styleable.ButtonCompat is not int.
W/XWalkInternalResources( 3425): org.xwalk.core.R$dimen.keyboard_accessory_fading_edge_length is not found.
W/XWalkInternalResources( 3425): org.xwalk.core.R$styleable.ButtonCompat is not int.
W/XWalkInternalResources( 3425): org.xwalk.core.R$dimen.keyboard_accessory_fading_edge_length is not found.
I/cr.base ( 3425): Extracting resource /data/data/com.novitrix.nerdhyve/app_xwalkcore/paks/xwalk.pak
I/cr.base ( 3425): Extracting resource /data/data/com.novitrix.nerdhyve/app_xwalkcore/icudtl.dat
D/XWalkLib( 3425): Post init xwalk core in com.novitrix.nerdhyve.MainActivity
D/XWalkLib( 3425): Init reserved class: class org.xwalk.core.XWalkPreferences
D/XWalkLib( 3425): Call reserved method: public static void org.xwalk.core.internal.XWalkPreferencesBridge.setValue(java.lang.String,boolean)
D/XWalkLib( 3425): Init reserved class: class org.xwalk.core.XWalkPreferences
D/XWalkLib( 3425): Call reserved method: public static void org.xwalk.core.internal.XWalkPreferencesBridge.setValue(java.lang.String,boolean)
D/XWalkLib( 3425): Init reserved class: class org.xwalk.core.XWalkPreferences
D/XWalkLib( 3425): Call reserved method: public static void org.xwalk.core.internal.XWalkPreferencesBridge.setValue(java.lang.String,boolean)
D/XWalkLib( 3425): Init reserved class: class org.xwalk.core.XWalkPreferences
D/XWalkLib( 3425): Call reserved method: public static void org.xwalk.core.internal.XWalkPreferencesBridge.setValue(java.lang.String,boolean)
D/XWalkLib( 3425): Init reserved object: class org.crosswalk.engine.XWalkCordovaView
E/chromium( 3425): [ERROR:xwalk_platform_notification_service.cc(103)] Not implemented reached in virtual bool xwalk::XWalkPlatformNotificationService::GetDisplayedPersistentNotifications(content::BrowserContext*, std::__1::set<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >*)
E/chromium( 3425): [ERROR:xwalk_browser_context.cc(79)] Failed to read preference, error num: 0
I/dalvikvm( 3425): Could not find method android.os.StatFs.getBlockSizeLong, referenced from method org.xwalk.core.internal.extension.api.device_capabilities.DeviceCapabilitiesStorage$StorageUnit.updateCapacity
D/XWalkLib( 3425): Init reserved object: class org.crosswalk.engine.XWalkCordovaResourceClient
D/XWalkLib( 3425): Call reserved method: public void org.xwalk.core.internal.XWalkViewBridge.setResourceClientSuper(org.xwalk.core.internal.XWalkResourceClientBridge)
D/XWalkLib( 3425): Init reserved object: class org.crosswalk.engine.XWalkCordovaUiClient
D/XWalkLib( 3425): Call reserved method: public void org.xwalk.core.internal.XWalkViewBridge.setUIClientSuper(org.xwalk.core.internal.XWalkUIClientBridge)
D/XWalkLib( 3425): Call reserved method: class org.xwalk.core.internal.XWalkViewBridge.setXWalkViewInternalVisibilitySuper
W/System.err( 3425): java.lang.UnsupportedOperationException: class org.xwalk.core.internal.XWalkViewBridge.setXWalkViewInternalVisibilitySuper
W/System.err( 3425): 	at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:57)
W/System.err( 3425): 	at org.xwalk.core.XWalkCoreWrapper.handlePostInit(XWalkCoreWrapper.java:169)
W/System.err( 3425): 	at org.xwalk.core.XWalkLibraryLoader$ActivateTask.onPostExecute(XWalkLibraryLoader.java:306)
W/System.err( 3425): 	at org.xwalk.core.XWalkLibraryLoader$ActivateTask.onPostExecute(XWalkLibraryLoader.java:277)
E/AndroidRuntime( 3425): java.lang.UnsupportedOperationException: class org.xwalk.core.internal.XWalkViewBridge.setXWalkViewInternalVisibilitySuper
E/AndroidRuntime( 3425): 	at org.xwalk.core.ReflectMethod.invoke(ReflectMethod.java:57)
E/AndroidRuntime( 3425): 	at org.xwalk.core.XWalkCoreWrapper.handlePostInit(XWalkCoreWrapper.java:169)
E/AndroidRuntime( 3425): 	at org.xwalk.core.XWalkLibraryLoader$ActivateTask.onPostExecute(XWalkLibraryLoader.java:306)
E/AndroidRuntime( 3425): 	at org.xwalk.core.XWalkLibraryLoader$ActivateTask.onPostExecute(XWalkLibraryLoader.java:277)
```

**Comment by fujunwei** [comment]
It can't be reproduced in our testing, It seems that the xwalk library isn't packaged to apk.

**Comment by booldplx** [comment]
me too....
