### ISSUE TITLE
Conflict between pushwoosh plugin and crosswalk plugin in ionic 2

### ISSUE THREAD

**Issue by jmickvs** [infil00p/cordova-crosswalk-engine#50]
Hello, I am using the cordova plugin-crosswalk but when I add the pushwoosh plugin to the project, the app no start because the app suddenly crash ("app was stopped").
In the android studio console I got the next log

Pub com.veureka.beopledev.firebaseinitprovider: com.google.firebase.provider.FirebaseInitProvider
FirebaseApp initialization unsuccessful
Could not find method android.app.Activity.checkSelfPermission, referenced from method org.apache.cordova.CordovaInterfaceImpl.hasPermission
VFY: unable to resolve virtual method 237: Landroid/app/Activity;.checkSelfPermission (Ljava/lang/String;)I
VFY: replacing opcode 0x6e at 0x0009
Could not find method android.app.Activity.requestPermissions, referenced from method org.apache.cordova.CordovaInterfaceImpl.requestPermissions
VFY: unable to resolve virtual method 291: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V
VFY: replacing opcode 0x6e at 0x000a
D/AndroidRuntime: Shutting down VM
threadid=1: thread exiting with uncaught exception (group=0x413442a0)
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.veureka.beopledev/com.veureka.beopledev.MainActivity}: java.lang.RuntimeException: Failed to create webview. 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
        at android.app.ActivityThread.access$700(ActivityThread.java:140)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4921)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: Failed to create webview. 
        at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:82)
        at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:196)
        at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:192)
        at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:141)
        at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214)
        at com.veureka.beopledev.MainActivity.onCreate(MainActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:5188)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135) 
        at android.app.ActivityThread.access$700(ActivityThread.java:140) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4921) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ClassNotFoundException: org.crosswalk.engine.XWalkWebViewEngine
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:217)
        at java.lang.Class.forName(Class.java:172)
        at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:78)
        at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:196) 
        at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:192) 
        at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:141) 
        at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214) 
        at com.veureka.beopledev.MainActivity.onCreate(MainActivity.java:32) 
        at android.app.Activity.performCreate(Activity.java:5188) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135) 
        at android.app.ActivityThread.access$700(ActivityThread.java:140) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4921) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.NoClassDefFoundError: org/crosswalk/engine/XWalkWebViewEngine
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:217) 
        at java.lang.Class.forName(Class.java:172) 
        at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:78) 
        at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:196) 
        at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:192) 
        at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:141) 
        at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214) 
        at com.veureka.beopledev.MainActivity.onCreate(MainActivity.java:32) 
        at android.app.Activity.performCreate(Activity.java:5188) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135) 
        at android.app.ActivityThread.access$700(ActivityThread.java:140) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4921) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.ClassNotFoundException: org.crosswalk.engine.XWalkWebViewEngine
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:217) 
        at java.lang.Class.forName(Class.java:172) 
        at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:78) 
        at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:196) 
        at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:192) 
        at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:141) 
        at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:214) 
        at com.veureka.beopledev.MainActivity.onCreate(MainActivity.java:32) 
        at android.app.Activity.performCreate(Activity.java:5188) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135) 
        at android.app.ActivityThread.access$700(ActivityThread.java:140) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4921) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805) 
        at dalvik.system.NativeStart.main(Native Method) 
GC_CONCURRENT freed 236K, 12% free 7292K/8199K, paused 6ms+2ms, total 37ms
I/Process: Sending signal. PID: 22718 SIG: 9

other information
Cordova CLI: 6.3.0
Ionic Framework Version: 2.0.0-beta.10
Ionic CLI Version: 2.0.0-beta.37
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID:	Deepin Description:	Deepin 15.2 
Node Version: v5.12.0

The plugins version
cordova-plugin-crosswalk-webview 1.8.0 "Crosswalk WebView Engine"
pushwoosh-cordova-plugin 6.2.0 "Pushwoosh"

I hope you can help me, thank you.

**Comment by fujunwei** [comment]
Do you mean it's work finely without pushwoosh plugin?

**Comment by jmickvs** [comment]
Yes, the app start fine without pushwoosh plugin but I need this plugin because I use the pushwoosh service for notifications, thank you.

**Comment by fujunwei** [comment]
Could you please file a bug in JIRA https://crosswalk-project.org/jira to track.

**Comment by jmickvs** [comment]
Sure

**Comment by fujunwei** [comment]
It can't be reproduced with following steps:

cordova create hello org.example.hello hello
cordova platform add android
cordova plugin add cordova-plugin-crosswalk-webview
cordova plugin add pushwoosh-cordova-plugin
cordova run

**Comment by jmickvs** [comment]
i did the same test and the app run without issues, now I will add all the plugins necesary for my app for try identify why it have this behavior, thank you.

**Comment by jmickvs** [comment]
Hello, the issue was resolved and not it was troble between crosswalk and pushwoosh plugin, I resolved it adding some configuration to the build.gradle and androidmanifiest of my project, thank you for support.
