### ISSUE TITLE
App crash when open on Android 4.4.2

### ISSUE THREAD

**Issue by ultimagz** [infil00p/cordova-crosswalk-engine#55]
My app always crash on start with crosswalk 19+. It happened on android 4.4 only, on android 5.0 and later app can run normally.
Here is the log.

`E/dalvikvm: Could not find class 'org.xwalk.core.XWalkActivityDelegate', referenced from method org.crosswalk.engine.XWalkWebViewEngine.<init>
W/dalvikvm: VFY: unable to resolve new-instance 8660 (Lorg/xwalk/core/XWalkActivityDelegate;) in Lorg/crosswalk/engine/XWalkWebViewEngine;
W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xwalk/core/XWalkView;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xwalk/core/XWalkView;)
W/dalvikvm: VFY: unable to find class referenced in signature (Lorg/xwalk/core/XWalkView;)
W/dalvikvm: VFY: unable to resolve virtual method 64438: Lorg/xwalk/core/XWalkView;.addJavascriptInterface (Ljava/lang/Object;Ljava/lang/String;)V
W/dalvikvm: Unable to resolve superclass of Lorg/crosswalk/engine/XWalkCordovaView; (8685)
W/dalvikvm: Link of class 'Lorg/crosswalk/engine/XWalkCordovaView;' failed
W/dalvikvm: Unable to resolve superclass of Lorg/crosswalk/engine/XWalkCordovaView; (8685)
W/dalvikvm: Link of class 'Lorg/crosswalk/engine/XWalkCordovaView;' failed
W/dalvikvm: VFY: unable to resolve virtual method 59313: Lorg/crosswalk/engine/XWalkCordovaView;.setVerticalScrollBarEnabled (Z)V
W/dalvikvm: Unable to resolve superclass of Lorg/crosswalk/engine/XWalkCordovaView; (8685)
W/dalvikvm: Link of class 'Lorg/crosswalk/engine/XWalkCordovaView;' failed
W/dalvikvm: Unable to resolve superclass of Lorg/crosswalk/engine/XWalkCordovaView; (8685)
W/dalvikvm: Link of class 'Lorg/crosswalk/engine/XWalkCordovaView;' failed
W/dalvikvm: VFY: unable to resolve virtual method 59295: Lorg/crosswalk/engine/XWalkCordovaView;.getExtensionManager ()Lorg/xwalk/core/XWalkExternalExtensionManager;
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: VFY: unable to resolve virtual method 64378: Lorg/xwalk/core/XWalkActivityDelegate;.isXWalkReady ()Z
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: VFY: unable to resolve virtual method 64378: Lorg/xwalk/core/XWalkActivityDelegate;.isXWalkReady ()Z
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: VFY: unable to resolve virtual method 64378: Lorg/xwalk/core/XWalkActivityDelegate;.isXWalkReady ()Z
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: VFY: unable to resolve virtual method 64378: Lorg/xwalk/core/XWalkActivityDelegate;.isXWalkReady ()Z
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: Link of class 'Lorg/xwalk/core/XWalkActivityDelegate;' failed
W/dalvikvm: VFY: unable to resolve virtual method 64378: Lorg/xwalk/core/XWalkActivityDelegate;.isXWalkReady ()Z
W/dalvikvm: Unable to resolve superclass of Lorg/crosswalk/engine/XWalkCordovaView; (8685)
W/dalvikvm: Link of class 'Lorg/crosswalk/engine/XWalkCordovaView;' failed
W/dalvikvm: VFY: returning Ljava/lang/Object; (cl=0x0), declared Landroid/view/View; (cl=0x0)
W/dalvikvm: VFY:  rejecting opcode 0x11 at 0x0002
W/dalvikvm: VFY:  rejected Lorg/crosswalk/engine/XWalkWebViewEngine;.getView ()Landroid/view/View;
W/dalvikvm: Verifier rejected class Lorg/crosswalk/engine/XWalkWebViewEngine;
W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x433101a0)
E/AndroidRuntime: FATAL EXCEPTION: main
`

And

`Process: com.appman.cordova.agentmate, PID: 5457
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.appman.cordova.agentmate/com.appman.cordova.agentmate.MainActivity}: java.lang.RuntimeException: Failed to create webview. 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464)
at android.app.ActivityThread.access$900(ActivityThread.java:172)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5653)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Failed to create webview. 
at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:82)
at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:195)
at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:192)
at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:141)
at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:213)
at com.appman.cordova.agentmate.MainActivity.onCreate(MainActivity.java:80)
at android.app.Activity.performCreate(Activity.java:5541)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464) 
at android.app.ActivityThread.access$900(ActivityThread.java:172) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:146) 
at android.app.ActivityThread.main(ActivityThread.java:5653) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.ClassNotFoundException: org.crosswalk.engine.XWalkWebViewEngine
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:251)
at java.lang.Class.forName(Class.java:216)
at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:78)
at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:195) 
at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:192) 
at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:141) 
at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:213) 
at com.appman.cordova.agentmate.MainActivity.onCreate(MainActivity.java:80) 
at android.app.Activity.performCreate(Activity.java:5541) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464) 
at android.app.ActivityThread.access$900(ActivityThread.java:172) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:146) 
at android.app.ActivityThread.main(ActivityThread.java:5653) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
at dalvik.system.NativeStart.main(Native Method) 
Caused by: java.lang.VerifyError: org/crosswalk/engine/XWalkWebViewEngine
at java.lang.Class.classForName(Native Method) 
at java.lang.Class.forName(Class.java:251) 
at java.lang.Class.forName(Class.java:216) 
at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:78) 
at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:195) 
at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:192) 
at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:141) 
at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:213) 
at com.appman.cordova.agentmate.MainActivity.onCreate(MainActivity.java:80) 
at android.app.Activity.performCreate(Activity.java:5541) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2368) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2464) 
at android.app.ActivityThread.access$900(ActivityThread.java:172) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:146) 
at android.app.ActivityThread.main(ActivityThread.java:5653) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107) 
at dalvik.system.NativeStart.main(Native Method) `

**Comment by fujunwei** [comment]
Could you please file a bug in JIRA https://crosswalk-project.org/jira
